### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by NigHTmxRE-in** [SealedSaucer/Online-Forever#12]
it shows an error while running the code 
the error is - "module *discord* not found" even if i try to run the code properly or in the correct manner, pleaase help me to find a solution to this problem, thank you

**Comment by usernmaerrf** [comment]
pip install discord

**Comment by AndrewTechnolgies** [comment]
after a lot of fighting I got the discord module installed, and it wasn’t as simple as “pip install discord” instead I had to install the module directly in the Online-Forever repl path. I did the same with flask but flask is trying to import markupsafe, and it can’t. I feel like this is an issue with repl.

**Comment by SealedSaucer** [comment]
It is indeed a replit issue. I am trying to figure out a workaround for this.

**Comment by SealedSaucer** [comment]
There shouldn't be any issue now.
