### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by RyanZuZi** [SealedSaucer/Online-Forever#14]
The owner of this website (discord.com) has banned you temporarily from accessing this website.
Access denied | discord.com used Cloudflare to restrict access</title>
<meta charset="UTF-8"

Any suggestions?

**Comment by RyanZuZi** [comment]
I've deleted and re-cloned it multiple times. And after about an hour, I'm hit with that error again.

**Comment by SealedSaucer** [comment]
Hm, it seems like an error with replit and not the code. Try typing `kill 1` in the shell and run the repl again.
