### ISSUE TITLE
discord.errors.LoginFailure: Improper token has been passed.

### ISSUE THREAD

**Issue by Bluscream** [SealedSaucer/Online-Forever#16]
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
discord.errors.LoginFailure: Improper token has been passed.

**Comment by SealedSaucer** [comment]
Your token is invalid.

**Comment by Bluscream** [comment]
I used the exact token right now. So i know it isnt invalid

**Comment by SealedSaucer** [comment]
The error is because either:
1. Your token is invalid
2. Replit installed discord.py instead of discord.py-self

Since discord.py don't support user accounts anymore, it will give you an error when you try to run it.

**Comment by Bluscream** [comment]
> The error is because either:
> 1. Your token is invalid
> 2. Replit installed discord.py instead of discord.py-self
> 
> Since discord.py don't support user accounts anymore, it will give you an error when you try to run it.

Ahh. Thanks that was it!
