### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by mewzax** [SealedSaucer/Online-Forever#19]
man is really selling a token onliner lmfao

**Comment by SealedSaucer** [comment]
Not forcing anyone ¯\_(ツ)_/¯

I might change it to requests and websockets in the near future so it won't need to depend a package.

**Comment by SealedSaucer** [comment]
Updated the code.

**Comment by mewzax** [comment]
i will post mine one day i think

**Comment by mewzax** [comment]
golang >>>
https://github.com/mewzax/Discord-Token-Aliver

**Comment by SealedSaucer** [comment]
Looks good 👍

Golang is faster than Python, I didn't make this tool in Golang because most of the people can't even figure out this code without the tutorial video. So, yeah... Good work tho.

**Comment by mewzax** [comment]
lul
