### ISSUE TITLE
Add way to set custom status

### ISSUE THREAD

**Issue by lodipo308** [SealedSaucer/Online-Forever#4]
Why you deleted my issue, you could just close it as others do.

It's possible, I don't use it for bot account.

**Comment by lodipo308** [comment]
https://discordpy.readthedocs.io/en/stable/api.html?highlight=change_presence#discord.CustomActivity

**Comment by SealedSaucer** [comment]
Try it. Or send me a screenshot of a bot/account using it.

**Comment by lodipo308** [comment]
Im not python dev, just suggesting new feature that will be useful for users

**Comment by lodipo308** [comment]
Or you can use this https://github.com/LeonardSSH/auto-discord-status/blob/main/main.py#L150

**Comment by SealedSaucer** [comment]
I am using discord.py for this code. If you are not aware, discord.py is no longer maintained. And also, please search your questions on google or other search engines before making an issue.

Danny (the creator of discord.py) himself told you won't be able to use custom statuses on discord. It is a discord limitation. I can't do anything on it.

Link to the discussion : https://github.com/Rapptz/discord.py/issues/2400

**Comment by Tenshi147** [comment]
With discord.py the closest you can get to this would be
![image](https://user-images.githubusercontent.com/57001729/151701977-708ed382-82b5-4969-ae5b-6105b3b96776.png)

**Comment by lodipo308** [comment]
Can you check this? https://github.com/LeonardSSH/auto-discord-status/blob/main/main.py#L150

**Comment by lodipo308** [comment]
> With discord.py the closest you can get to this would be ![image](https://user-images.githubusercontent.com/57001729/151701977-708ed382-82b5-4969-ae5b-6105b3b96776.png)

And how to do it?

**Comment by SealedSaucer** [comment]
Yes. Or "competing with". I have already made a selfbot that exhibit similar properties https://github.com/SealedSaucer/Gamecord and https://github.com/SealedSaucer/Fake-Streamer.

**Comment by Tenshi147** [comment]
@lodipo308 I made a pull request #5  with the code I used to make that possible
