### ISSUE TITLE
missing 3 required positional arguments

### ISSUE THREAD

**Issue by Samekas123** [SealedSaucer/Online-Forever#43]
Using a fresh ubuntu 22 install and getting the following error:

I have already done `pip install websocket-client` as on the documentation but it was already installed.

```
Traceback (most recent call last):
  File "/root/Online-Forever/main.py", line 85, in <module>
    run_onliner()
  File "/root/Online-Forever/main.py", line 81, in run_onliner
    onliner(usertoken, status)
  File "/root/Online-Forever/main.py", line 31, in onliner
    ws = websocket.WebSocket()
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket'                , and 'rfile'
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
```

**Comment by Samekas123** [comment]
Fixed

**Comment by siamskoi** [comment]
> Fixed

How?

**Comment by Samekas123** [comment]
> > Fixed
> 
> How?

1. First do `pip uninstall websocket`
2. Make sure all websocket modules  were removed by listing the current modules isntalled `pip list | grep websocket` then `pip uninstall "MODULEHERE"` if any it's there.
3. pip install websocket-client

Rerun the main script, that should fix it.

**Comment by siamskoi** [comment]
@Samekas123 thank you!

**Comment by Samekas123** [comment]
> @Samekas123 thank you!

Np, let me know if it works for you.

**Comment by Clyde-Timonera** [comment]
it installs the conflicting package again.

**Comment by Clyde-Timonera** [comment]
still the same on replit and local

**Comment by Milou4Dev** [comment]
> still the same on replit and local

You can use a golang version that I or siamskoi made. It should work without a problem.

https://github.com/Milou4Dev/ProjectDGT

&

https://github.com/siamskoi/discrod-online

**Comment by SealedSaucer** [comment]
Closing the issue since it's solved.
