### ISSUE TITLE
getting this error and account not getting online

### ISSUE THREAD

**Issue by AKGamingYT0** [SealedSaucer/Online-Forever#46]
Traceback (most recent call last):
  File "/home/runner/24x7/main.py", line 85, in <module>
    run_onliner()
  File "/home/runner/24x7/main.py", line 81, in run_onliner
    onliner(usertoken, status)
  File "/home/runner/24x7/main.py", line 31, in onliner
    ws = websocket.WebSocket()
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

**Comment by SealedSaucer** [comment]
Refer to this: [Link](https://github.com/SealedSaucer/Online-Forever#replit-typeerror-websocket__init-missing-3-required-positional-arguments-environ-socket-and-rfile)

**Comment by AKGamingYT0** [comment]
tried but not working

**Comment by SealedSaucer** [comment]
Try the method in #43 

1. First, do `pip uninstall websocket`.
2. Make sure all websocket modules were removed by listing the currently installed modules with `pip list | grep websocket`. 
3. Then, run `pip uninstall 'MODULEHERE'` if any are listed.
4. Finally, run `pip install websocket-client`.

**Comment by SealedSaucer** [comment]
What's the error now?

**Comment by SealedSaucer** [comment]
Closing the issue due to inactivity.
