### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by Botgamerns10s** [SealedSaucer/Online-Forever#52]
After the service goes live for around a minute it gives this error. My account is successfully logged in though cuz I can see my username when it goes live 
![IMG_20241019_110538](https://github.com/user-attachments/assets/f4701075-0c2a-46fd-a561-9a7155e8751e)
![IMG_20241019_110515](https://github.com/user-attachments/assets/2d14229d-95af-465f-8dcc-e7eda9a87332)
![IMG_20241019_110350](https://github.com/user-attachments/assets/bb620f1e-b3e7-44c4-a8de-eace419d7a4c)

**Comment by Botgamerns10s** [comment]
Anyone here to help 🙏

**Comment by NekoSakuraLucia** [comment]
### What are the symptoms of the problem? It should be clearly stated. ❗

**Comment by Botgamerns10s** [comment]
It is just closing saying that the websocket received a very big message

**Comment by NekoSakuraLucia** [comment]
> It is just closing saying that the websocket received a very big message

### Is it still showing an error now?

**Comment by Samekas123** [comment]
It disconnects from me also after 1 minute or so.

**Comment by Botgamerns10s** [comment]
Ahh I deleted the script now nvm 😅

**Comment by SealedSaucer** [comment]
I haven't used Render and cannot give you any support on this, sorry.
