### ISSUE TITLE
Connection drops after a few seconds.

### ISSUE THREAD

**Issue by Samekas123** [SealedSaucer/Online-Forever#53]
Running it locally, the connection drops after a few seconds. It first goes online, then goes offline again after a few seconds, with no errors showing.

**Comment by NekoSakuraLucia** [comment]
Could it be because of the heartbeat being sent?

**Comment by Samekas123** [comment]
Not sure what you mean. Tested on 3 different vps, always the same.

**Comment by Samekas123** [comment]
I fixed the code, working fine now.
