### ISSUE TITLE
[FIXED] Script is also calling other websites

### ISSUE THREAD

**Issue by therealjaredcodling** [SealedSaucer/Online-Forever#7]
Script is calling other websites, a site I'm assuming you own, https://phantomcodes.ga/support

It's calling it from keep_alive.py

This site, then redirects to shady looking sites which you're rotating.

This is straight-up malware.

**Comment by SealedSaucer** [comment]
I used to own the domain phantomcodes.ga, but, it's now sniped/taken from me and it belongs to someone else.

And by doing a whois search you will see the current owners of the domain

![image](https://user-images.githubusercontent.com/71928730/153413264-18544d6e-f7dc-4cba-9c27-65a20acc49a2.png)

Thanks for reporting this tho, I will change the link in the code.

**Comment by therealjaredcodling** [comment]
No worries, thanks for the update. Best of luck with it, seems like quite
the horror story, hopefully you save a few people from suffering the same.
