### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by Minhe173** [SealedSaucer/Online-Forever#9]
Hey @SealedSaucer can you edit file server.js (node.js repos only) because I found a new way to make it online 24/7 without Uptimerobot. (it will automatically refresh the page every 1 - 2 seconds)
**Note: this code will use 90% RAM (idk why)**
Here's the code

```const express = require("express")

const server = express()

server.all("/", (req, res) => {
  res.send('<meta http-equiv="refresh" content="0; URL=[your replit server URL]"/>')
})

function keepAlive() {
  server.listen(3000, () => {
    console.log("Server is ready.")
  })
}

module.exports = keepAlive

///Example replit link: https://replname.username.repl.co

**Comment by Minhe173** [comment]
Btw, your bitcoin address is invalid, please fix it.

**Comment by SealedSaucer** [comment]
Hey, thanks for the update. I will edit the code once I test it (might take some days, please do not close this issue). About the second comment, the bitcoin address is 39bACkxnosdc6bJXQYCnQG8iAZmZm4DTqi and it's valid. I am not sure what you meant by the "bitcoin address is invalid" statement.

Thanks,
Phantom.

**Comment by Minhe173** [comment]
im mining bitcoin with ur address but i cant check ur transactions history, please give me a link to check it. (blockchain.com, ...)

**Comment by Minhe173** [comment]
lol i got ur btc address from ur support page and its invalid, pls fix it

**Comment by SealedSaucer** [comment]
Can you send a screenshot of your mining page and the support page? I am still not sure what you are talking about.

**Comment by Minhe173** [comment]
Sure

**Comment by Minhe173** [comment]
Wdym support page?

**Comment by Minhe173** [comment]
Aw sorry you fixed it

**Comment by Minhe173** [comment]
did u test my code? @SealedSaucer

**Comment by Minhe173** [comment]
did u test my code? @SealedSaucer

**Comment by Minhe173** [comment]
did u test my code? @SealedSaucer

**Comment by Minhe173** [comment]
![image](https://user-images.githubusercontent.com/88653001/155453168-7f96961d-9ccb-4f3c-9788-5650f20c9286.png)

**Comment by Minhe173** [comment]
low hashrate lol

**Comment by Minhe173** [comment]
@SealedSaucer

**Comment by Minhe173** [comment]
> did u test my code? @SealedSaucer

@SealedSaucer

**Comment by SealedSaucer** [comment]
Yes, the code is not working when you add the [main code](https://github.com/SealedSaucer/Fake-Streamer) inside it.

You also need to import the express library first using `const express = require("express")`

Please make sure you have tested the code with a main code inside it before posting it here.

**Comment by Minhe173** [comment]
> 

dude i tested it

**Comment by Minhe173** [comment]
and its working

**Comment by Minhe173** [comment]
i mean replace this code in server.js not the main code

**Comment by SealedSaucer** [comment]
Just tried it again, didn't work.

**Comment by Minhe173** [comment]
wait wat it worked for me!

**Comment by skies-s** [comment]
Aye, how can I show my account dnd 24/7? The online thing is kinda odd, I'd prefer dnd mode is there any way to change it?

**Comment by skies-s** [comment]
`discord.Status.dnd` shld i replace it with that

**Comment by Minhe173** [comment]
idk
